"""posts table

Revision ID: 447216ecb9ab
Revises: 28431bd567bc
Create Date: 2020-06-13 16:17:15.110315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447216ecb9ab'
down_revision = '28431bd567bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
